
/****** Object:  Table dbo.CHT011_SESSION   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT011_SESSION') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT011_SESSION
GO

/****** Object:  Table dbo.CHT020_EVENTRESULT   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT020_EVENTRESULT') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT020_EVENTRESULT
GO

/****** Object:  Table dbo.ZZT516_AREA   ******/
if exists (select * from sysobjects where id = object_id('dbo.ZZT516_AREA') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.ZZT516_AREA
GO

/****** Object:  Table dbo.ZZT016_AREA   ******/
if exists (select * from sysobjects where id = object_id('dbo.ZZT016_AREA') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.ZZT016_AREA
GO

/****** Object:  Table dbo.CHT010_SPLIT_MATCH_RESULT   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT010_SPLIT_MATCH_RESULT') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT010_SPLIT_MATCH_RESULT
GO


/****** Object:  Table dbo.CHT007_SPLIT_POOL_RESULT   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT007_SPLIT_POOL_RESULT') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT007_SPLIT_POOL_RESULT
GO

/****** Object:  Table dbo.CHT009_MATCH_RESULT   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT009_MATCH_RESULT') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT009_MATCH_RESULT
GO

/****** Object:  Table dbo.CHT012_MATCH_MEMBER   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT012_MATCH_MEMBER') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT012_MATCH_MEMBER
GO

/****** Object:  Table dbo.CHT008_MATCH   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT008_MATCH') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT008_MATCH
GO

/****** Object:  Table dbo.CHT006_POOL_RESULT   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT006_POOL_RESULT') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT006_POOL_RESULT
GO

/****** Object:  Table dbo.CHT002_MEMBER   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT002_MEMBER') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT002_MEMBER
GO

/****** Object:  Table dbo.ZCH018_MEDALLIST   ******/
if exists (select * from sysobjects where id = object_id('dbo.ZCH018_MEDALLIST') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.ZCH018_MEDALLIST
GO

/****** Object:  Table dbo.CHT001_INSCRIPTION   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT001_INSCRIPTION') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT001_INSCRIPTION
GO

/****** Object:  Table dbo.CHT005_POOL   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT005_POOL') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT005_POOL
GO

/****** Object:  Table dbo.CHT003_PHASE   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT003_PHASE') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT003_PHASE
GO

/****** Object:  Table dbo.CHT000_DEFINITION   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT000_DEFINITION') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT000_DEFINITION
GO

/****** Object:  Table dbo.ZCH029_PROG_MATCH_POSITION   ******/
if exists (select * from sysobjects where id = object_id('dbo.ZCH029_PROG_MATCH_POSITION') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.ZCH029_PROG_MATCH_POSITION
GO

/****** Object:  Table dbo.ZCH024_ROUND   ******/
if exists (select * from sysobjects where id = object_id('dbo.ZCH024_ROUND') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.ZCH024_ROUND
GO


/****** Object:  Table dbo.ZCH026_WEATHER_CONDITIONS   ******/
if exists (select * from sysobjects where id = object_id('dbo.ZCH026_WEATHER_CONDITIONS') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.ZCH026_WEATHER_CONDITIONS
GO

/****** Object:  Table dbo.ZCH028_PROG_POOL_POSITION   ******/
if exists (select * from sysobjects where id = object_id('dbo.ZCH028_PROG_POOL_POSITION') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.ZCH028_PROG_POOL_POSITION
GO

/****** Object:  Table dbo.ZCH023_MODALITY_PHASE   ******/
if exists (select * from sysobjects where id = object_id('dbo.ZCH023_MODALITY_PHASE') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.ZCH023_MODALITY_PHASE
GO

/****** Object:  Table dbo.ZCH512_PHASE   ******/
if exists (select * from sysobjects where id = object_id('dbo.ZCH512_PHASE') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.ZCH512_PHASE
GO

/****** Object:  Table dbo.ZCH012_PHASE   ******/
if exists (select * from sysobjects where id = object_id('dbo.ZCH012_PHASE') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.ZCH012_PHASE
GO

/****** Object:  Table dbo.ZCH511_EVENT   ******/
if exists (select * from sysobjects where id = object_id('dbo.ZCH511_EVENT') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.ZCH511_EVENT
GO

/****** Object:  Table dbo.ZCH011_EVENT   ******/
if exists (select * from sysobjects where id = object_id('dbo.ZCH011_EVENT') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.ZCH011_EVENT
GO


/****** Object:  Table dbo.CHT568_TEAM_MATCH_CNFG   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT568_TEAM_MATCH_CNFG') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT568_TEAM_MATCH_CNFG
GO

/****** Object:  Table dbo.CHT068_TEAM_MATCH_CNFG   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT068_TEAM_MATCH_CNFG') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT068_TEAM_MATCH_CNFG
GO

/****** Object:  Table dbo.ZCH510_REGISTER   ******/
if exists (select * from sysobjects where id = object_id('dbo.ZCH510_REGISTER') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.ZCH510_REGISTER
GO

/****** Object:  Table dbo.ZCH010_REGISTER   ******/
if exists (select * from sysobjects where id = object_id('dbo.ZCH010_REGISTER') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.ZCH010_REGISTER
GO

/****** Object:  Table dbo.ZCH509_QUALITATIVE   ******/
if exists (select * from sysobjects where id = object_id('dbo.ZCH509_QUALITATIVE') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.ZCH509_QUALITATIVE
GO

/****** Object:  Table dbo.ZCH009_QUALITATIVE   ******/
if exists (select * from sysobjects where id = object_id('dbo.ZCH009_QUALITATIVE') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.ZCH009_QUALITATIVE
GO

/****** Object:  Table dbo.CHT017_JUDGE   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT017_JUDGE') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT017_JUDGE
GO

/****** Object:  Table dbo.CHT013_MATCH_JUDGE   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT013_MATCH_JUDGE') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT013_MATCH_JUDGE
GO

/****** Object:  Table dbo.CHT061_SPLIT_MATCH   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT061_SPLIT_MATCH') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT061_SPLIT_MATCH
GO

/****** Object:  Table dbo.ZCH031_COURT   ******/
if exists (select * from sysobjects where id = object_id('dbo.ZCH031_COURT') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.ZCH031_COURT
GO

/****** Object:  Table dbo.ZCH531_COURT   ******/
if exists (select * from sysobjects where id = object_id('dbo.ZCH531_COURT') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.ZCH531_COURT
GO

/****** Object:  Table dbo.CHT014_CLUB   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT014_CLUB') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT014_CLUB
GO

/****** Object:  Table dbo.CHT064_MASTER_TYPE   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT064_MASTER_TYPE') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT064_MASTER_TYPE
GO

/****** Object:  Table dbo.CHT564_MASTER_TYPE   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT564_MASTER_TYPE') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT564_MASTER_TYPE
GO

/****** Object:  Table dbo.CHT062_RATING_DIF   ******/
if exists (select * from sysobjects where id = object_id('dbo.CHT062_RATING_DIF') and OBJECTPROPERTY(id, 'IsUserTable') = 1)
	drop table dbo.CHT062_RATING_DIF
GO
/****** Object:  Table dbo.ZZT016_AREA    ******/
CREATE TABLE dbo.ZZT016_AREA (
	AREA char (3) NOT NULL ,
	PARENT char (3) NULL ,
	RLEVEL tinyint NOT NULL ,
	CONSTRAINT PK_ZZT016_AREA PRIMARY KEY  CLUSTERED 
	(
		AREA
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.ZZT516_AREA    ******/
CREATE TABLE dbo.ZZT516_AREA (
	AREA char (3) NOT NULL ,
	IDLANGUAGE char (3) NOT NULL ,
	LDESCRIPTION nvarchar (35) NULL CONSTRAINT DF_ZZT516_AREA_LDESCRIPTION DEFAULT (null),
	SDESCRIPTION nvarchar (20) NULL CONSTRAINT DF_ZZT516_AREA_SDESCRIPTION DEFAULT (null),
	RLDESCRIPTION nvarchar (35) NULL CONSTRAINT DF_ZZT516_AREA_RLDESCRIPTION DEFAULT (null) ,
	RSDESCRIPTION nvarchar (20) NULL CONSTRAINT DF_ZZT516_AREA_RSDESCRIPTION DEFAULT (null),
	CONSTRAINT PK_ZZT516_AREA PRIMARY KEY  CLUSTERED 
	(
		AREA,
		IDLANGUAGE
	) WITH  FILLFACTOR = 90
)
GO
/****** Object:  Table dbo.ZCH018_MEDALLIST  ******/
CREATE TABLE dbo.ZCH018_MEDALLIST (
	SEX char(1) NOT NULL,
	EVENT char(3) NOT NULL,
	REGISTER int NOT NULL,
	MEDAL tinyint NOT NULL ,
	ACHIEVEMENT_DATE datetime NULL,
	MARK varchar(15) NULL, 
	CONSTRAINT PK_ZCH018_MEDALLIST PRIMARY KEY  CLUSTERED 
	(
		SEX,
		EVENT,
		REGISTER,
		MEDAL
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.ZCH009_QUALITATIVE    ******/
CREATE TABLE dbo.ZCH009_QUALITATIVE (
	QUALITATIVE char(1) NOT NULL ,
	NORDER tinyint NULL,
	CONSTRAINT PK_ZCH009_QUALITATIVE PRIMARY KEY  CLUSTERED 
	(
		QUALITATIVE
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.ZCH509_QUALITATIVE    ******/
CREATE TABLE dbo.ZCH509_QUALITATIVE (
	QUALITATIVE char(1) NOT NULL ,
	IDLANGUAGE char (3) NOT NULL ,
	LDESCRIPTION nvarchar (35) NULL CONSTRAINT DF_ZCH509_QUALITATIVE_LDESCRIPTION DEFAULT (null),
	SDESCRIPTION nvarchar (20) NULL CONSTRAINT DF_ZCH509_QUALITATIVE_SDESCRIPTION DEFAULT (null),
	CONSTRAINT PK_ZCH509_QUALITATIVE PRIMARY KEY  CLUSTERED 
	(
		QUALITATIVE,
		IDLANGUAGE
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.ZCH011_EVENT    ******/
CREATE TABLE dbo.ZCH011_EVENT (
	SEX char(1)  NOT NULL ,
	EVENT char(3)  NOT NULL ,
	FORMAT varchar(12) NULL CONSTRAINT DF_ZCH011_EVENT_FORMAT DEFAULT (null),
	START_DATE datetime NULL CONSTRAINT DF_ZCH011_EVENT_START_DATE DEFAULT (null),
	START_TIME datetime NULL CONSTRAINT DF_ZCH011_EVENT_START_TIME DEFAULT (null),
	END_DATE datetime NULL CONSTRAINT DF_ZCH011_EVENT_END_DATE DEFAULT (null),
	END_TIME datetime NULL CONSTRAINT DF_ZCH011_EVENT_END_TIME DEFAULT (null),
	STATUS smallint NULL CONSTRAINT DF_ZCH011_EVENT_STATUS DEFAULT (0),
	ENABLE smallint NOT NULL  CONSTRAINT DF_ZCH011_EVENT_ENABLE DEFAULT (0),
	MEDICAL_CLASS varchar (15) NULL CONSTRAINT DF_ZCH011_EVENT_MEDICAL_CLASS DEFAULT (null),
	MEDALS_BY_MC tinyint NOT NULL CONSTRAINT DF_ZCH011_EVENT_MEDALS_BY_MC DEFAULT (0),
	MODALITY smallint NULL CONSTRAINT DF_ZCH011_EVENT_MODALITY DEFAULT (0),
	ORDER_EVENT smallint NULL CONSTRAINT DF_ZCH011_EVENT_ORDER_EVENT DEFAULT (0),
	TWO_BRONCES smallint NULL CONSTRAINT DF_ZCH011_EVENT_TWO_BRONCES DEFAULT (0),
	MODE smallint NULL CONSTRAINT DF_ZCH011_EVENT_MODE DEFAULT (0),
	TYPE_EVENT smallint NULL CONSTRAINT DF_ZCH011_EVENT_TYPE_EVENT DEFAULT (0),
	REQRANKORDER nvarchar (20) NULL CONSTRAINT DF_ZCH011_EVENT_REQRKORDER DEFAULT (null),
	TEAMCFG smallint NULL CONSTRAINT DF_ZCH011_EVENT_TEAMCFG DEFAULT (0),
	CONST_RATING float NULL,
	POINTS_BYE float NULL,
	CONSTRAINT PK_ZCH011_EVENT PRIMARY KEY  CLUSTERED 
	(
		SEX,
		EVENT
	) WITH  FILLFACTOR = 90

) 
GO

/****** Object:  Table dbo.ZCH511_EVENT     ******/
CREATE TABLE dbo.ZCH511_EVENT (
	SEX char(1) NOT NULL ,
	EVENT char(3) NOT NULL,
	IDLANGUAGE char (3) NOT NULL ,
	LDESCRIPTION nvarchar (35) NULL CONSTRAINT DF_ZCH511_EVENT_LDES DEFAULT (null),
	SDESCRIPTION nvarchar (20) NULL CONSTRAINT DF_ZCH511_EVENT_SDES DEFAULT (null),
	RLDESCRIPTION nvarchar (35) NULL CONSTRAINT DF_ZCH511_EVENT_RLDES DEFAULT (null),
	RSDESCRIPTION nvarchar (20) NULL CONSTRAINT DF_ZCH511_EVENT_RSDES DEFAULT (null),
	CONSTRAINT PK_ZCH511_EVENT PRIMARY KEY  CLUSTERED 
	(
		SEX,
		EVENT,
		IDLANGUAGE
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.ZCH012_PHASE    ******/
CREATE TABLE dbo.ZCH012_PHASE (
	PHASE char(1)  NOT NULL ,
	NORDER smallint NOT NULL CONSTRAINT DF_ZCH012_PHASE_NORDER DEFAULT (0),
	WINNER_RANK smallint NULL CONSTRAINT DF_ZCH012_PHASE_WINNER_RANK DEFAULT (0),	
	LOSER_RANK smallint NULL CONSTRAINT DF_ZCH012_PHASE_LOSER_RANK DEFAULT (0),	
	TYPEPHASE smallint NULL CONSTRAINT DF_ZCH012_TYPEPHASE DEFAULT (0),
	CONSTRAINT PK_ZCH012_PHASE PRIMARY KEY  CLUSTERED 
	(
		PHASE
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.ZCH512_PHASE     ******/
CREATE TABLE dbo.ZCH512_PHASE (
        PHASE char(1) NOT NULL ,
	IDLANGUAGE char (3) NOT NULL ,
	LDESCRIPTION nvarchar (35) NULL CONSTRAINT DF_ZCH512_PHASE_LDES DEFAULT (null),
	SDESCRIPTION nvarchar (20) NULL CONSTRAINT DF_ZCH512_PHASE_SDES DEFAULT (null),
	CONSTRAINT PK_ZCH512_PHASE PRIMARY KEY  CLUSTERED 
	(
		PHASE,
		IDLANGUAGE
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.ZCH010_REGISTER     ******/
CREATE TABLE dbo.ZCH010_REGISTER (
	SEX char (1)  NOT NULL ,
	NUMBER int NOT NULL,
	COUNTRY char (3) NULL CONSTRAINT DF_ZCH010_REGISTER_COUNTRY DEFAULT (null),
	TYPE tinyint NOT NULL CONSTRAINT DF_ZCH010_REGISTER_TYPE DEFAULT (0),
	CLUB char (3)  NULL CONSTRAINT DF_ZCH010_REGISTER_CLUB DEFAULT (null),
	FEDERATION char (3) NULL CONSTRAINT DF_ZCH010_REGISTER_FEDERATION DEFAULT (null),
	CATEGORY char(1) NULL CONSTRAINT DF_ZCH010_REGISTER_CATE DEFAULT (null),
	ACREDITATION varchar (15) NOT NULL CONSTRAINT DF_ZCH010_REGISTER_ACRED DEFAULT (null),
	BIRTH_DATE datetime NULL CONSTRAINT DF_ZCH010_REGISTER_BIRTH_DATE DEFAULT (null),
	HEIGHT_CM int NULL CONSTRAINT DF_ZCH010_REGISTER_HEIGHT_CM DEFAULT (null),
	WEIGHT_GR int NULL CONSTRAINT DF_ZCH010_REGISTER_WEIGHT_GR DEFAULT (null),
	FLG_RECORD tinyint NULL CONSTRAINT DF_ZCH010_REGISTER_FRECORD DEFAULT (null),
	FLG_TOP tinyint NULL CONSTRAINT DF_ZCH010_REGISTER_FTOP DEFAULT (null),
	FLG_COMP tinyint NULL CONSTRAINT DF_ZCH010_REGISTER_COMP DEFAULT (null),
	ISO_COUNTRY char (3)  NULL CONSTRAINT DF_ZCH010_REGISTER_ISO_COUNTRY DEFAULT (null),
	IF_NUMBER varchar (16)  NULL CONSTRAINT DF_ZCH010_REGISTER_IF_NUMBER DEFAULT (null),
	TEAMCODE varchar (15)  NULL CONSTRAINT DF_ZCH010_REGISTER_TEAMCODE DEFAULT (null),
	IOC_NUMBER varchar (25)  NULL CONSTRAINT DF_ZCH010_REGISTER_IOC_NUMBER DEFAULT (null),
	MEDICAL_CLASS varchar (15) NULL CONSTRAINT DF_ZCH010_REGISTER_MEDICAL_CLASS DEFAULT (null),
	NACIONALITY char (3)  NULL CONSTRAINT DF_ZCH010_REGISTER_ISO_NACIONALITY DEFAULT (null),
	ORGID varchar (4)  NULL CONSTRAINT DF_ZCH010_REGISTER_ORGID DEFAULT (null),
	MASTER_TYPE smallint NULL CONSTRAINT DF_ZCH010_REGISTER_MASTER_TYPE DEFAULT (null),
	CONSTRAINT PK_ZCH010_REGISTER PRIMARY KEY  CLUSTERED 
	(
		NUMBER
	) WITH  FILLFACTOR = 90
) 
GO

/****** Object:  Table dbo.ZCH510_REGISTER     ******/
CREATE TABLE dbo.ZCH510_REGISTER (
	NUMBER int NOT NULL ,
	IDLANGUAGE char (3)  NOT NULL ,
	NAME1 nvarchar (25)  NULL CONSTRAINT DF_ZCH510_REGISTER_NAME1 DEFAULT (null),
	NAME2 nvarchar (35)  NULL CONSTRAINT DF_ZCH510_REGISTER_NAME2 DEFAULT (null),
	PRNLNAME nvarchar (35)  NULL CONSTRAINT DF_ZCH510_REGISTER_PRNLNAME DEFAULT (null),
	PRNSNAME nvarchar (20) NULL CONSTRAINT DF_ZCH510_REGISTER_PRNSNAME DEFAULT (null),
	TVLNAME nvarchar (51)  NULL CONSTRAINT DF_ZCH510_REGISTER_TVLNAME DEFAULT (null),
	TVSNAME nvarchar (30)  NULL CONSTRAINT DF_ZCH510_REGISTER_TVSNAME DEFAULT (null),
	SCBLNAME nvarchar (20)  NULL CONSTRAINT DF_ZCH510_REGISTER_SCBLNAME DEFAULT (null),
	SCBSNAME nvarchar (20)  NULL CONSTRAINT DF_ZCH510_REGISTER_SCBSNAME DEFAULT (null),
	LMCNAME2 nvarchar (35)  NULL CONSTRAINT DF_ZCH510_REGISTER_LMCNAME2 DEFAULT (null),
	CONSTRAINT PK_ZCH510_REGISTER PRIMARY KEY  CLUSTERED 
	(
		NUMBER,
		IDLANGUAGE
	) WITH  FILLFACTOR = 90
) 
GO

/****** Object:  Table dbo.ZCH023_MODALITY_PHASE    ******/
CREATE TABLE dbo.ZCH023_MODALITY_PHASE (
	MODALITY smallint NOT NULL ,
	PHASE char (1)  NOT NULL ,
	POOL_DESCRIPTION smallint NOT NULL CONSTRAINT DF_ZCH023_MODALITY_POOL_DES DEFAULT (1),
	ISPOOL tinyint NOT NULL CONSTRAINT DF_ZCH023_MODALITY_IS_POOL DEFAULT (0),
	N_POOLS smallint NOT NULL CONSTRAINT DF_ZCH023_MODALITY_NPOOLS DEFAULT (0),
	N_POOL_COMPETITORS smallint NOT NULL CONSTRAINT DF_ZCH023_MODALITY_NPOOL_COMP DEFAULT (0),
	N_POOL_ROUNDS smallint NOT NULL CONSTRAINT DF_ZCH023_MODALITY_NPOOL_ROUND DEFAULT (0),
	N_MATCHS smallint NOT NULL CONSTRAINT DF_ZCH023_MODALITY_NMATCHS DEFAULT (0),
	N_MATCH_COMPETITORS smallint NOT NULL CONSTRAINT DF_ZCH023_MODALITY_NMATCH_COMP DEFAULT (0),
	N_SPLITS smallint NOT NULL CONSTRAINT DF_ZCH023_MODALITY_NSPLITS DEFAULT (0),
	ORDER_PHASE smallint NOT NULL CONSTRAINT DF_ZCH023_MODALITY_NORDER_PHASE DEFAULT (0),
	WINNER_RANK smallint NULL CONSTRAINT DF_ZCH023_MODALITY_WINNER_RANK DEFAULT (0),	
	LOSER_RANK smallint NULL CONSTRAINT DF_ZCH023_MODALITY_LOSER_RANK DEFAULT (0),	
	SUBMATCHES_MEMBERS varchar(50) NULL CONSTRAINT DF_ZCH023_MODALITY_SUBMATCHES_MEMBERS DEFAULT (null),	
	CONSTRAINT PK_ZCH023_MODALITY_PHASE PRIMARY KEY  CLUSTERED 
	(
		MODALITY,
		PHASE
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.ZCH024_ROUND    ******/
CREATE TABLE dbo.ZCH024_ROUND (
	SEX char(1)  NOT NULL ,
	EVENT char(3)  NOT NULL ,
	ROUND char(1)  NOT NULL ,
	NORDER smallint  NULL CONSTRAINT DF_ZCH024_ROUND_NORDER DEFAULT (0) ,
	NCLASSIFIED smallint NULL CONSTRAINT DF_ZCH024_ROUND_NCLASSIFIED DEFAULT (0) ,
	STATUS smallint NOT NULL CONSTRAINT DF_ZCH024_ROUND_STATUS DEFAULT (0),
	START_DATE datetime NULL CONSTRAINT DF_ZCH024_ROUND_START_DATE DEFAULT (null),
	START_TIME datetime NULL CONSTRAINT DF_ZCH024_ROUND_START_TIME DEFAULT (null),
	END_DATE datetime NULL CONSTRAINT DF_ZCH024_ROUND_END_DATE DEFAULT (null),
	END_TIME datetime NULL CONSTRAINT DF_ZCH024_ROUND_END_TIME DEFAULT (null),
	CONSTRAINT PK_ZCH024_ROUND PRIMARY KEY  CLUSTERED 
	(
		SEX,
		EVENT,
		ROUND
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.ZCH026_WEATHER_CONDITIONS    ******/
CREATE TABLE dbo.ZCH026_WEATHER_CONDITIONS (
	VENUE char(3)  NOT NULL ,
	ID smallint NOT NULL ,
	CURRENTDATE datetime NOT NULL CONSTRAINT DF_ZCH026_WEATHER_DATE DEFAULT (null),
	CURRENTTIME datetime NOT NULL CONSTRAINT DF_ZCH026_WEATHER_TIME DEFAULT (null),
	WEATHER tinyint  NULL ,
	AIR_TEMPERATURE smallint NULL ,
	HUMIDITY smallint NULL ,
	WIND_DIRECTION varchar (35)  NULL ,
	WIND_SPEED varchar (25)  NULL ,
	BAR_PRESSURE int NULL ,
	CONSTRAINT PK_ZCH026_WEATHER_CONDITIONS PRIMARY KEY  CLUSTERED 
	(
		VENUE,
		ID
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.ZCH028_PROG_POOL_POSITION    ******/
CREATE TABLE dbo.ZCH028_PROG_POOL_POSITION (
	MODALITY smallint NOT NULL ,
	PHASE_CODE char(1) NOT NULL ,
	POOL_CODE smallint NOT NULL ,
	IDPOSITION smallint NOT NULL ,
	PHASE_LUCKY_LOSER char (1) NULL ,
    	PHASE_SOURCE char (1) NULL,
	POOL_SOURCE smallint NOT NULL ,
	RANKING_SOURCE smallint NOT NULL CONSTRAINT DF_ZCH028_PROG_POOL_RANKING DEFAULT (0),
	ISBEST tinyint NOT NULL CONSTRAINT DF_ZCH028_PROG_POOL_ISBEST DEFAULT (0),
	POSITION_SOURCE smallint NOT NULL CONSTRAINT DF_ZCH028_PROG_POOL_POSITION_SOURCE DEFAULT (0),
	CONSTRAINT PK_ZCH028_PROG_POOL_POSITION PRIMARY KEY  CLUSTERED 
	(
		MODALITY,
		PHASE_CODE,
		POOL_CODE,
		IDPOSITION
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.ZCH029_PROG_MATCH_POSITION    ******/
CREATE TABLE dbo.ZCH029_PROG_MATCH_POSITION (
	MODALITY smallint NOT NULL ,
	PHASE_CODE char(1) NOT NULL ,
	POOL_CODE smallint NOT NULL ,
	MATCH_CODE smallint NOT NULL ,
	MATCH_POSITION smallint NOT NULL ,
	POOL_POSITION smallint NOT NULL CONSTRAINT DF_zCH029_PROG_MATCH_POOL_POSI DEFAULT (0),
	CONSTRAINT PK_ZCH029_PROG_MATCH_POSITION PRIMARY KEY  CLUSTERED 
	(
		MODALITY,
		PHASE_CODE,
		POOL_CODE,
		MATCH_CODE,
		MATCH_POSITION	
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.ZCH031_COURT    ******/
CREATE TABLE dbo.ZCH031_COURT (
	VENUE char(3)  NOT NULL ,
	COURT smallint NOT NULL ,
	NORDER smallint NULL CONSTRAINT DF_ZCH031_COURT DEFAULT (0),
	CONSTRAINT PK_ZCH031_COURT PRIMARY KEY  CLUSTERED 
	(
		VENUE,
		COURT
	) WITH  FILLFACTOR = 90
) 
GO

/****** Object:  Table dbo.ZCH531_COURT    ******/
CREATE TABLE dbo.ZCH531_COURT (
	VENUE char(3)  NOT NULL ,
	COURT smallint NOT NULL ,
	IDLANGUAGE char (3) NOT NULL ,
	LDESCRIPTION varchar (35) NULL CONSTRAINT DF_ZCH531_COURT_LDES DEFAULT (null),
	SDESCRIPTION varchar (20) NULL CONSTRAINT DF_ZCH531_COURT_SDES DEFAULT (null),
	CONSTRAINT PK_ZCH531_COURT PRIMARY KEY  CLUSTERED 
	(
		VENUE,
		COURT,
		IDLANGUAGE
	) WITH  FILLFACTOR = 90
) 
GO


/****** Object:  Table dbo.CHT000_DEFINITION    ******/
CREATE TABLE dbo.CHT000_DEFINITION (
	DISCIPLINE char (2) NOT NULL ,
	GROUPING tinyint NULL CONSTRAINT DF_CHT000_DEF_GROUPING DEFAULT (0),
	WEIGHT varchar (6) NOT NULL CONSTRAINT DF_CHT000_DEFINITION_WEIGHT DEFAULT ('###.#'),
	HEIGHT varchar (6) NOT NULL CONSTRAINT DF_CHT000_DEFINITION_HEIGHT DEFAULT ('#.##'),
	CHAMP char (3) NULL,
	LSCB_LENGTH tinyint NULL CONSTRAINT DF_CHT000_DEFINITION_LSCB DEFAULT (15), 
	SSCB_LENGTH tinyint NULL CONSTRAINT DF_CHT000_DEFINITION_SSCB DEFAULT (10),
	STATUS tinyint NULL CONSTRAINT DF_CHT000_DEFINITION_STATUS DEFAULT (0),
	PARALYMPIC tinyint NOT NULL CONSTRAINT DF_CHT000_DEFINITION_PARALYMPIC DEFAULT (0),
	RSC_MODE tinyint NULL  CONSTRAINT DF_SWT000_DEFINITION_RSC_MODE DEFAULT (0),
	RSC_COMPOSITION varchar (15) NULL,
	AUTO_PROG tinyint NULL CONSTRAINT DF_CHT000_DEFINITION_AUTO_PROG DEFAULT (0),
	ABSENCE_POINTS float NULL CONSTRAINT DF_CHT006_POOL_RESULT_ABS_PTS DEFAULT (0.5),
	CONSTRAINT PK_CHT000_DEFINITION PRIMARY KEY  CLUSTERED 
	(
		DISCIPLINE
	) WITH  FILLFACTOR = 90
)
GO


/****** Object:  Table dbo.CHT001_INSCRIPTION    ******/
CREATE TABLE dbo.CHT001_INSCRIPTION (
	SEX char(1)  NOT NULL ,
	EVENT char(3)  NOT NULL ,
	REGISTER int NOT NULL ,
	SEED smallint NULL CONSTRAINT DF_CHT001_INSCRIPTION_SEED DEFAULT (0),
	RATING int NULL CONSTRAINT DF_CHT001_INSCRIPTION_RATING DEFAULT (0),
	KCONST smallint NULL CONSTRAINT DF_CHT001_INSCRIPTION_KCONST DEFAULT (0),
	CONSTRAINT PK_CHT001_INSCRIPTION PRIMARY KEY  CLUSTERED 
	(
		SEX,
		EVENT,
		REGISTER
	) WITH  FILLFACTOR = 90
) 
GO

/****** Object:  Table dbo.CHT002_MEMBER    ******/
CREATE TABLE dbo.CHT002_MEMBER (
	SEX char (1) NOT NULL ,
	EVENT char (3) NOT NULL ,
	REGISTER int NOT NULL ,
	MEMBER int NOT NULL ,
	NORDER smallint NULL CONSTRAINT DF_CHT002_MEMBER_NORDER DEFAULT (0),
	IDFUNCTION tinyint NOT NULL CONSTRAINT DF_CHT002_MEMBER_IDFUNCTION DEFAULT (0),	
	RATING int NULL CONSTRAINT DF_CHT002_MEMBER_RATING DEFAULT (0),
	KCONST smallint NULL CONSTRAINT DF_CHT002_MEMBER_KCONST DEFAULT (0),
	CONSTRAINT PK_CHT002_MEMBER PRIMARY KEY  CLUSTERED 
	(
		SEX,
		EVENT,
		REGISTER,
		MEMBER
	) WITH  FILLFACTOR = 90
) 
GO

/****** Object:  Table dbo.CHT003_PHASE    ******/
CREATE TABLE dbo.CHT003_PHASE (
	SEX char(1)  NOT NULL ,
	EVENT char(3)  NOT NULL ,
	PHASE char (1)  NOT NULL ,
	ORDER_EXECUTION smallint NOT NULL CONSTRAINT DF_CHT003_PHASE_ORDER_EXECUTION DEFAULT (0),
	START_DATE datetime NULL CONSTRAINT DF_CHT003_PHASE_START_DATE DEFAULT (null),
	START_TIME datetime NULL CONSTRAINT DF_CHT003_PHASE_START_TIME DEFAULT (null),
	END_DATE datetime NULL CONSTRAINT DF_CHT003_PHASE_END_DATE DEFAULT (null),
	END_TIME datetime NULL CONSTRAINT DF_CHT003_PHASE_END_TIME DEFAULT (null),
	STATUS tinyint NOT NULL CONSTRAINT DF_CHT003_PHASE_STATUS DEFAULT (0),
	IS_POOL tinyint NOT NULL CONSTRAINT DF_CHT003_PHASE_IS_POOL DEFAULT (0),
	POOL_DESCRIPTION tinyint NOT NULL CONSTRAINT DF_CHT003_PHASE_POOL_DESC DEFAULT (0),
	POOLS_NUMBER smallint NOT NULL CONSTRAINT DF_CHT003_PHASE_POOL_NUMBER DEFAULT (0),
	SPLITS_NUMBER smallint NOT NULL CONSTRAINT DF_CHT003_PHASE_SPLITS_NUMBER DEFAULT (0),
	WINNER_RANK smallint NULL CONSTRAINT DF_CHT003_PHASE_WINNER_RANK DEFAULT (0),	
	LOSER_RANK smallint NULL CONSTRAINT DF_CHT003_PHASE_LOSER_RANK DEFAULT (0),	
	SUBMATCHES_MEMBERS varchar(50) NULL CONSTRAINT DF_CHT003_PHASE_SUBMATCHES_MEMBERS DEFAULT (null),
	TYPEPHASE smallint NULL CONSTRAINT DF_CHT003_TYPEPHASE DEFAULT (0),	
	TEAM_MATCH_CNFG smallint NULL CONSTRAINT DF_CHT003_TEAM_MATCH_CNFG DEFAULT (0),
	CONSTRAINT PK_CHT003_PHASE PRIMARY KEY  CLUSTERED 
	(
		SEX,
		EVENT,
		PHASE
	) WITH  FILLFACTOR = 90
) 
GO

/****** Object:  Table dbo.CHT005_POOL    ******/
CREATE TABLE dbo.CHT005_POOL (
	SEX char(1)  NOT NULL ,
	EVENT char(3) NOT NULL ,
	PHASE char(1) NOT NULL ,
	POOL smallint NOT NULL ,
	NORDER smallint NOT NULL ,
	NCOMPETITORS smallint NULL CONSTRAINT DF_CHT005_POOL_NCOMPETITORS DEFAULT (0),
	NROUNDS smallint NULL CONSTRAINT DF_CHT005_POOL_NROUNDS DEFAULT (0),
	NMATCHES smallint NULL CONSTRAINT DF_CHT005_POOL_NMATCHES DEFAULT (0),
	STATUS tinyint NOT NULL CONSTRAINT DF_CHT005_POOL_STATUS DEFAULT (0),
	START_DATE datetime NULL CONSTRAINT DF_CHT005_POOL_START_DATE DEFAULT (null),
	START_TIME datetime NULL CONSTRAINT DF_CHT005_POOL_START_TIME DEFAULT (null),
	END_DATE datetime NULL  CONSTRAINT DF_CHT005_POOL_END_DATE DEFAULT (null),
	END_TIME datetime NULL  CONSTRAINT DF_CHT005_POOL_END_TIME DEFAULT (null),
	CONSTRAINT PK_CHT005_POOL PRIMARY KEY  CLUSTERED 
	(
		SEX,
		EVENT,
		PHASE,
		POOL
	) WITH  FILLFACTOR = 90

)
GO

/****** Object:  Table dbo.CHT020_EVENTRESULT    ******/
CREATE TABLE dbo.CHT020_EVENTRESULT (
	SEX char(1)  NOT NULL ,
	EVENT char (3) NOT NULL ,
	REGISTER int NOT NULL ,
	RANK smallint NULL CONSTRAINT DF_CHT020_EVENTRESULT_RANK DEFAULT (0),
	RANKPO smallint NULL CONSTRAINT DF_CHT020_EVENTRESULT_RANKPO DEFAULT (0),
	QUALITATIVE char (1) NOT NULL CONSTRAINT DF_CHT020_EVENTRESULT_QUALITATIVE DEFAULT (0),
	RATING int NULL CONSTRAINT DF_DF_CHT020_EVENTRESULT_RATING DEFAULT (0),
	CONSTRAINT PK_CHT020_EVENTRESULT PRIMARY KEY  CLUSTERED 
	(
		SEX,
		EVENT,
		REGISTER
	) WITH  FILLFACTOR = 90
) 
GO

/****** Object:  Table dbo.CHT061_SPLIT_MATCH    ******/
CREATE TABLE dbo.CHT061_SPLIT_MATCH (
	SEX char(1) NOT NULL ,
	EVENT char(3) NOT NULL ,
	PHASE char(1) NOT NULL ,
	POOL smallint NOT NULL ,
	IDMATCH smallint NOT NULL ,
	SPLIT smallint NOT NULL ,
	STATUS tinyint NOT NULL CONSTRAINT DF_CHT061_SPL_MAT_STATUS DEFAULT (10),
	CONSTRAINT PK_CHT061_SPLIT_MATCH PRIMARY KEY  CLUSTERED
	(
		SEX,
		EVENT,
		PHASE,
		POOL, 
		IDMATCH, 
		SPLIT
	) WITH  FILLFACTOR = 90
) 
GO



/****** Object:  Table dbo.CHT006_POOL_RESULT    ******/
CREATE TABLE dbo.CHT006_POOL_RESULT (
	SEX char(1)  NOT NULL ,
	EVENT char (3) NOT NULL ,
	PHASE char (1) NOT NULL ,
	POOL smallint NOT NULL ,
	IDPOSITION smallint NOT NULL ,
	NUMBER int NULL CONSTRAINT DF_CHT006_POOL_RESULT_NUMBER DEFAULT (NULL) ,
	RANKING smallint  NULL CONSTRAINT DF_CHT006_POOL_RESULT_RANKING DEFAULT (0) ,
	RANKING_PO smallint  NULL CONSTRAINT DF_CHT006_POOL_RESULT_RANKINGPO DEFAULT (0) ,
	POINTS char (10) NULL CONSTRAINT DF_CHT006_POOL_RESULT_POINTS DEFAULT (null),
	PHASE_LUCKY_LOSER char(1) NULL CONSTRAINT DF_CHT006_POOL_RESULT_PHASE_LUCKY_LOSER DEFAULT (null),
	PHASE_SOURCE char(1) NULL CONSTRAINT DF_CHT006_POOL_RESULT_PHASE_SOURCE DEFAULT (null),
	POOL_SOURCE smallint NULL CONSTRAINT DF_CHT006_POOL_RESULT_POOL_SOURCE DEFAULT (0),
	RANKING_SOURCE smallint NULL CONSTRAINT DF_CHT006_POOL_RESULT_RANKING_SOURCE DEFAULT (0),
	QUALITATIVE char(1) NOT NULL CONSTRAINT DF_CHT006_POOL_RESULT_QUALITATIVE DEFAULT ('0'),
	PHASE_RANK smallint NULL CONSTRAINT DF_CHT006_POOL_RESULT_PHASE_RANK DEFAULT (0),
	PHASE_RANK_PO smallint NULL CONSTRAINT DF_CHT006_POOL_RESULT_PHASE_RANK_PO DEFAULT (0),
	ISBYE tinyint NULL CONSTRAINT DF_CHT006_POOL_RESULT_ISBYE DEFAULT (0),
	ISBEST tinyint NULL CONSTRAINT DF_CHT006_POOL_RESULT_ISBEST DEFAULT (0),
	POSITION_SOURCE smallint NULL CONSTRAINT DF_CHT006_POOL_RESULT_POSITION_SOURCE DEFAULT (0),
	MATCHES_PLAYED smallint NULL CONSTRAINT DF_CHT006_POOL_RESULT_MATCHES_PLAYED DEFAULT (0),
	WON_GAMES smallint NULL CONSTRAINT DF_CHT006_POOL_RESULT_WON_GAMES DEFAULT (0),
	LOST_GAMES smallint NULL CONSTRAINT DF_CHT006_POOL_RESULT_LOST_GAMES DEFAULT (0),
	TIE_GAMES smallint NULL CONSTRAINT DF_CHT006_POOL_RESULT_TIE_GAMES DEFAULT (0),
	POINTS_F float NULL CONSTRAINT DF_CHT006_POOL_RESULT_POINTS_F DEFAULT (0.0),
	SOLKOFF float NULL CONSTRAINT DF_CHT006_POOL_RESULT_SOLKOFF DEFAULT (0.0),
	MEDIAN_SOLKOFF float NULL CONSTRAINT DF_CHT006_POOL_RESULT_MEDIANSOLKOFF DEFAULT (0.0),
	SONNEBERGER float NULL CONSTRAINT DF_CHT006_POOL_RESULT_SONNEBERGER DEFAULT (0.0),
	PROGRESSIVE_SCORE float NULL CONSTRAINT DF_CHT006_POOL_RESULT_PROGRESSIVE_SCORE DEFAULT (0.0),
	CONSTRAINT PK_CHT006_POOL_RESULT PRIMARY KEY  CLUSTERED 
	(
		SEX,
		EVENT,
		PHASE,
		POOL,
		IDPOSITION
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.CHT007_SPLIT_POOL_RESULT    ******/
CREATE TABLE dbo.CHT007_SPLIT_POOL_RESULT (
	SEX char (1)  NOT NULL ,
	EVENT char (3)  NOT NULL ,
	PHASE char (1)  NOT NULL ,
	POOL smallint NOT NULL ,
	POOL_RESULT smallint NOT NULL ,
	SPLIT smallint NOT NULL ,
	CONSTRAINT PK_CHT007_SPLIT_POOL_RESULT PRIMARY KEY  CLUSTERED 
	(
		SEX,
		EVENT,
		PHASE,
		POOL,
		POOL_RESULT,
		SPLIT
	) WITH  FILLFACTOR = 90
) 
GO

/****** Object:  Table dbo.CHT008_MATCH    ******/
CREATE TABLE dbo.CHT008_MATCH (
	SEX char(1)  NOT NULL ,
	EVENT char(3) NOT NULL ,
	PHASE char(1) NOT NULL ,
	POOL smallint NOT NULL ,
	IDMATCH smallint NOT NULL ,
	STATUS smallint NOT NULL CONSTRAINT DF_CHT008_MATCH_STATUS DEFAULT (0),
	MATCH_NUM smallint NOT NULL CONSTRAINT DF_CHT008_MATCH_MATCH_NUM DEFAULT (0),
	START_TIME datetime NULL CONSTRAINT DF_CHT008_MATCH_START_TIME DEFAULT (null),
	START_DATE datetime NULL CONSTRAINT DF_CHT008_MATCH_START_DATE DEFAULT (null),
	END_TIME datetime NULL CONSTRAINT DF_CHT008_MATCH_END_TIME DEFAULT (null),
	END_DATE datetime NULL CONSTRAINT DF_CHT008_MATCH_END_DATE DEFAULT (null),
	NUM_COMPETITORS smallint NOT NULL CONSTRAINT DF_CHT008_MATCH_NUM_COMP DEFAULT (0),
	IS_TIE_BREAK tinyint NOT NULL CONSTRAINT DF_CHT008_MATCH_IS_TIE DEFAULT (0),
	HISTORIC image NULL CONSTRAINT DF_CHT008_MATCH_HISTORIC DEFAULT (null),
	VENUE char (3) NULL CONSTRAINT DF_CHT008_MATCH_ID_VENUE DEFAULT (null),
	COURT smallint NULL CONSTRAINT DF_CHT008_MATCH_ID_COURT DEFAULT (null),
	IDSESSION char (1) NULL CONSTRAINT DF_CHT008_MATCH_SESSION DEFAULT (0),
	IDSUBMATCH smallint NOT NULL CONSTRAINT DF_CHT008_MATCH_IDSUBMATCH DEFAULT (0),
	IDTYPE tinyint NOT NULL CONSTRAINT DF_CHT008_MATCH_IDTYPE DEFAULT (-1),
	ROUND smallint NULL CONSTRAINT DF_CHT008_MATCH_ROUND DEFAULT (null),
	CONSTRAINT PK_CHT008_MATCH PRIMARY KEY  CLUSTERED 
	(
		SEX,
		EVENT,
		PHASE,
		POOL,
		IDMATCH
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.CHT009_MATCH_RESULT    ******/
CREATE TABLE dbo.CHT009_MATCH_RESULT (
	SEX char(1) NOT NULL,
	EVENT char(3) NOT NULL, 
	PHASE char(1) NOT NULL,
	POOL smallint NOT NULL ,
	IDMATCH smallint NOT NULL ,
	IDPOSITION smallint NOT NULL ,
	NUMBER int NULL CONSTRAINT DF_CHT009_MATCH_RESULT_NUMBER DEFAULT (NULL),
	QUALITATIVE char (1) NOT NULL DEFAULT ('0'),
	RANKING smallint NOT NULL CONSTRAINT DF_CHT009_MATCH_RESULT_RANKING DEFAULT (0),
	RANKING_POSITION smallint NOT NULL CONSTRAINT DF_CHT009_MATCH_RESULT_RANKINGPO DEFAULT (0),
	CODE_UNIFORM varchar (50) NULL CONSTRAINT DF_CHT009_MATCH_RESULT_CODE_UNIFORM DEFAULT (NULL),
	POOL_POSITION smallint NOT NULL CONSTRAINT DF_CHT009_MATCH_RESULT_POOL_POSI DEFAULT (0),
	ISBYE tinyint NULL CONSTRAINT DF_CHT009_MATCH_RESULT_ISBYE DEFAULT (0),
	POINTS float NULL,	
	IDSUBMATCH smallint NOT NULL CONSTRAINT DF_CHT009_MATCH_RESULT_IDSUBMATCH DEFAULT (0),
	UPFLOATER tinyint NULL CONSTRAINT DF_CHT009_MATCH_RESULT_UPFLOATER DEFAULT (0),
	DOWNFLOATER tinyint NULL CONSTRAINT DF_CHT009_MATCH_RESULT_DOWNFLOATER DEFAULT (0),
	COLOR smallint NOT NULL CONSTRAINT DF_CHT009_MATCH_RESULT_COLOR DEFAULT (0),
	CONSTRAINT PK_CHT009_MATCH_RESULT PRIMARY KEY  CLUSTERED 
	(
		SEX,
		EVENT,
		PHASE,
		POOL,
		IDMATCH,
		IDPOSITION
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.CHT010_SPLIT_MATCH_RESULT    ******/
CREATE TABLE dbo.CHT010_SPLIT_MATCH_RESULT (
	SEX char (1) NOT NULL ,
	EVENT char (3) NOT NULL ,
	PHASE char (1) NOT NULL ,
	POOL smallint NOT NULL ,
	IDMATCH smallint NOT NULL ,
	MATCH_RESULT smallint NOT NULL ,
	SPLIT smallint NOT NULL ,
	CONSTRAINT PK_CHT010_SPLIT_MATCH_RESULT PRIMARY KEY  CLUSTERED 
	(
		SEX,
		EVENT,
		PHASE,
		POOL,
		IDMATCH,
		MATCH_RESULT,
		SPLIT
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.CHT012_MATCH_MEMBER    ******/
CREATE TABLE dbo.CHT012_MATCH_MEMBER (
	SEX char(1)  NOT NULL ,
	EVENT char(3)  NOT NULL ,
	PHASE char(1)  NOT NULL ,
	POOL smallint NOT NULL ,
	IDMATCH smallint NOT NULL ,
	MATCH_RESULT smallint NOT NULL ,
	MATCH_MEMBER smallint NOT NULL ,
	NUMBER int NULL ,
	ACTIVE tinyint NOT NULL,
	IDSUBMATCH smallint NOT NULL CONSTRAINT DF_CHT012_MATCH_MEMBER DEFAULT (0),
	CONSTRAINT PK_CHT012_MATCH_MEMBER PRIMARY KEY  CLUSTERED 
	(
		SEX,
		EVENT,
		PHASE,
		POOL,
		IDMATCH,
		MATCH_RESULT,
		MATCH_MEMBER
	) WITH  FILLFACTOR = 90
)
GO


/****** Object:  Table dbo.CHT011_SESSION    ******/
CREATE TABLE dbo.CHT011_SESSION (
	IDSESSION char(1)  NOT NULL ,
	CURRENTDATE datetime NOT NULL CONSTRAINT DF_CHT011_SESSION_CURRENTDATE DEFAULT (null),
	CURRENTTIME datetime NULL CONSTRAINT DF_CHT011_SESSION_CURRENTTIME DEFAULT (0),
	NAME nvarchar (35) NULL CONSTRAINT DF_CHT011_SESSION_NAME DEFAULT (null),
	ACUM_SESS smallint NULL CONSTRAINT DF_CHT011_SESSION_ACUM_SESS DEFAULT (0),
	STATUS smallint NULL CONSTRAINT DF_CHT011_SESSION_STATUS DEFAULT (0),
	CONSTRAINT PK_CHT011_SESSION PRIMARY KEY  CLUSTERED 
	(
		IDSESSION,
		CURRENTDATE	
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.CHT017_JUDGE******/
CREATE TABLE dbo.CHT017_JUDGE (
	REGISTER int NOT NULL ,
	IDFUNCTION tinyint NOT NULL,
	CONSTRAINT PK_CHT017_JUDGE PRIMARY KEY  CLUSTERED 
	(
		REGISTER,
		IDFUNCTION
	) WITH  FILLFACTOR = 90
)
GO


/****** Object:  Table dbo.CHT013_MATCH_JUDGE    ******/
CREATE TABLE dbo.CHT013_MATCH_JUDGE (
	SEX char(1)  NOT NULL ,
	EVENT char(3) NOT NULL ,
	PHASE char(1) NOT NULL ,
	POOL smallint NOT NULL ,
	IDMATCH smallint NOT NULL ,
	IDFUNCTION tinyint NOT NULL ,
	NUMBER int NOT NULL,
	IDPOSITION tinyint NULL CONSTRAINT DF_CHT013_MATCH_JUDGE_POSI DEFAULT (null),
	N_ORDER smallint NULL CONSTRAINT DF_CHT013_MATCH_JUDGE_N_ORDER DEFAULT (null),
	CONSTRAINT PK_CHT013_MATCH_JUDGE PRIMARY KEY  CLUSTERED 
	(
		SEX,
		EVENT,
		PHASE,
		POOL,
		IDMATCH,
		IDFUNCTION,
		NUMBER	
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.CHT564_MASTER_TYPE    ******/
CREATE TABLE dbo.CHT564_MASTER_TYPE (
	MASTER_TYPE smallint NOT NULL,
	IDLANGUAGE char (3) NOT NULL ,
	LDESCRIPTION nvarchar (35) NULL CONSTRAINT DF_CHT564_MASTER_TYPE_LDESCRIPTION DEFAULT (null),
	SDESCRIPTION nvarchar (20) NULL CONSTRAINT DF_CHT564_MASTER_TYPE_SDESCRIPTION DEFAULT (null),
	CONSTRAINT PK_CHT564_MASTER_TYPE PRIMARY KEY CLUSTERED 
	(
		MASTER_TYPE,
		IDLANGUAGE
	) WITH  FILLFACTOR = 90
) 
GO

/****** Object:  Table dbo.CHT064_MASTER_TYPE    ******/
CREATE TABLE dbo.CHT064_MASTER_TYPE (
	MASTER_TYPE smallint NOT NULL,
	NORDER smallint NULL CONSTRAINT DF_CHT064_MASTER_TYPE_NORDER DEFAULT (0),
	CONSTRAINT PK_CHT064_MASTER_TYPE PRIMARY KEY CLUSTERED 
	(
		MASTER_TYPE
	) WITH  FILLFACTOR = 90
) 
GO

/****** Object:  Table dbo.CHT568_TEAM_MATCH_CNFG    ******/
CREATE TABLE dbo.CHT568_TEAM_MATCH_CNFG(
	TEAMCFG smallint NOT NULL ,
	IDLANGUAGE char (3) NOT NULL ,
	SDESCRIPTION nvarchar (20) NULL CONSTRAINT DF_CHT568_TEAM_MATCH_CNFG_SDESCRIPTION DEFAULT (null),
	LDESCRIPTION nvarchar (35) NULL CONSTRAINT DF_CHT568_TEAM_MATCH_CNFG_LDESCRIPTION DEFAULT (null),
	CONSTRAINT PK_CHT568_TEAM_MATCH_CNFG PRIMARY KEY  CLUSTERED 
	(
		TEAMCFG,
		IDLANGUAGE
	) WITH  FILLFACTOR = 90
)
GO

/****** Object:  Table dbo.CHT068_TEAM_MATCH_CNFG    ******/
CREATE TABLE dbo.CHT068_TEAM_MATCH_CNFG(
	TEAMCFG smallint NOT NULL ,
	NCOMPETITORS smallint NULL ,
	NMATCHES smallint NULL ,
	NMATCHESTYPE char (40) NULL , 
	COMPMATCHESDISTRIBUTION char (60) NULL ,
	FAWAYC char (1) NULL ,
	CONSTRAINT PK_CHT068_TEAM_MATCH_CNFG PRIMARY KEY  CLUSTERED 
	(
		TEAMCFG
	) WITH  FILLFACTOR = 90
)
GO
/****** Object:  Table dbo.CHT062_RATING_DIF    ******/
CREATE TABLE dbo.CHT062_RATING_DIF (
	CODE_RAT smallint NOT NULL,
	PROBABILITY smallint NULL CONSTRAINT DF_CHT062_RATING_DIF_PROBABILITY DEFAULT (0),
	DIFFERENCE smallint NULL CONSTRAINT DF_CHT062_RATING_DIF_DIFFERENCE DEFAULT (0),
	CONSTRAINT PK_CHT062_RATING_DIF PRIMARY KEY CLUSTERED 
	(
		CODE_RAT
	) WITH  FILLFACTOR = 90
) 
GO
/*_______________________________________________________________________________________*/
/*_______________________________________________________________________________________*/
/*_______________________________________________________________________________________*/
/*_______________________________________________________________________________________*/



GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT568_TEAM_MATCH_CNFG TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT068_TEAM_MATCH_CNFG TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON ZCH018_MEDALLIST TO mslGroup
GO
GRANT   SELECT  ON ZCH009_QUALITATIVE TO mslGroup
GO
GRANT   SELECT  ON ZCH509_QUALITATIVE TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON ZCH010_REGISTER TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON ZCH510_REGISTER TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON ZCH011_EVENT TO mslGroup
GO
GRANT    SELECT  ON ZCH511_EVENT TO mslGroup
GO
GRANT    SELECT ON ZCH012_PHASE TO mslGroup
GO
GRANT    SELECT ON ZCH512_PHASE TO mslGroup
GO
GRANT   SELECT   ON ZZT016_AREA  TO mslGroup
GO
GRANT 	SELECT   ON CHT064_MASTER_TYPE TO mslGroup
GO
GRANT 	SELECT   ON CHT564_MASTER_TYPE TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON ZCH023_MODALITY_PHASE TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON ZCH028_PROG_POOL_POSITION TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON ZCH029_PROG_MATCH_POSITION TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT017_JUDGE TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT000_DEFINITION TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT001_INSCRIPTION TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT002_MEMBER TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT003_PHASE TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT005_POOL TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT006_POOL_RESULT TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT007_SPLIT_POOL_RESULT TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT008_MATCH TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT009_MATCH_RESULT TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT013_MATCH_JUDGE TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT010_SPLIT_MATCH_RESULT TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT011_SESSION TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT012_MATCH_MEMBER TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT020_EVENTRESULT TO mslGroup
GO
GRANT SELECT ON ZCH031_COURT TO mslGroup
GO
GRANT SELECT ON ZCH531_COURT TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT061_SPLIT_MATCH TO mslGroup
GO
GRANT SELECT, REFERENCES, INSERT, DELETE, UPDATE ON ZCH024_ROUND  TO mslGroup
GO
GRANT SELECT, REFERENCES, INSERT, DELETE, UPDATE ON ZCH026_WEATHER_CONDITIONS	TO mslGroup
GO
GRANT    REFERENCES ,  SELECT ,  INSERT ,  DELETE ,  UPDATE  ON CHT062_RATING_DIF TO mslGroup
GO
