
/****** Object:  Table dbo.ZCH564_MASTER_TYPE  ******/
ALTER TABLE  dbo.ZCH564_MASTER_TYPE 
	ADD
	CONSTRAINT FK_ZCH564_MASTER_TYPE_ZZT000_LANG FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES  dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZCH564_MASTER_TYPE_ZCH064_MASTER_TYPE FOREIGN KEY 
	(
		MASTER_TYPE
	) REFERENCES  dbo.ZCH064_MASTER_TYPE (
		MASTER_TYPE
	)
GO

/****** Object:  Table dbo.ZCH568_TEAM_MATCH_CNFG  ******/
ALTER TABLE  dbo.ZCH568_TEAM_MATCH_CNFG
	ADD
	CONSTRAINT FK_ZCH568_TEAM_MATCH_CNFG_ZZT000_LANG FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES  dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZCH568_TEAM_MATCH_CNFG_ZCH068_TEAM_MATCH_CNFG FOREIGN KEY 
	(
		TEAMCFG
	) REFERENCES  dbo.ZCH068_TEAM_MATCH_CNFG (
		TEAMCFG
	)
GO