


ALTER TABLE  dbo.ZZT501_DISCIPLINE 
	ADD
	CONSTRAINT FK_ZZT501_DISC_ZZT000_LANG FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES  dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZZT501_DISC_ZZT001_DISC FOREIGN KEY 
	(
		DISCIPLINE
	) REFERENCES  dbo.ZZT001_DISCIPLINE (
		DISCIPLINE
	)

GO


/****** Object:  Table dbo.ZZT502_SEX   ******/
ALTER TABLE  dbo.ZZT502_SEX 
	ADD
	CONSTRAINT FK_ZZT502_SEX_ZZT000_LANGUAGE FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES  dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZZT502_SEX_ZZT002_SEX FOREIGN KEY 
	(
		SEX
	) REFERENCES dbo.ZZT002_SEX (
		SEX
	)

GO


/****** Object:  Table dbo.ZZT503_COUNTRY    ******/
ALTER  TABLE  dbo.ZZT503_COUNTRY 
	ADD
	CONSTRAINT FK_ZZT503_COUN_ZZT000_LANG FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES  dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZZT503_COUN_ZZT003_COUN FOREIGN KEY 
	(
		COUNTRY
	) REFERENCES  dbo.ZZT003_COUNTRY (
		COUNTRY
	)

GO

/****** Object:  Table dbo.ZZT504_CLUB  ******/
ALTER TABLE  dbo.ZZT504_CLUB 
	ADD
	CONSTRAINT FK_ZZT504_CLUB_ZZT000_LANGUAGE FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES  dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZZT504_CLUB_ZZT004_CLUB FOREIGN KEY 
	(
		CLUB
	) REFERENCES  dbo.ZZT004_CLUB (
		CLUB
	)

GO


/****** Object:  Table dbo.ZZT505_FEDERATION   ******/
ALTER TABLE  dbo.ZZT505_FEDERATION 
	ADD
	CONSTRAINT FK_ZZT505_FEDE_ZZT000_LANG FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES  dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZZT505_FEDE_ZZT005_FEDE FOREIGN KEY 
	(
		FEDERATION
	) REFERENCES  dbo.ZZT005_FEDERATION (
		FEDERATION
	)

GO
/****** Object:  Table dbo.ZZT506_VENUE  ******/
ALTER TABLE  dbo.ZZT506_VENUE 
	ADD
	CONSTRAINT FK_ZZT506_VENU_ZZT000_LANG FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES  dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZZT506_VENUE_ZZT006_VENUE FOREIGN KEY 
	(
		VENUE
	) REFERENCES  dbo.ZZT006_VENUE (
		VENUE
	)

GO

/****** Object:  Table dbo.ZZT507_CATEGORY   ******/
ALTER TABLE  dbo.ZZT507_CATEGORY 
	ADD
	CONSTRAINT FK_ZZT507_CATE_ZZT000_LANG FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES  dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZZT507_CATE_ZZT007_CATE FOREIGN KEY 
	(
		CATEGORY
	) REFERENCES  dbo.ZZT007_CATEGORY (
		CATEGORY
	)

GO

/****** Object:  Table dbo.ZZT508_CHAMPIONSHIP    ******/
ALTER TABLE  dbo.ZZT508_CHAMPIONSHIP 
	ADD
	CONSTRAINT FK_ZZT508_CHAM_ZZT008_CHAM FOREIGN KEY 
	(
		CHAMP
	) REFERENCES dbo.ZZT008_CHAMPIONSHIP (
		CHAMP
	),
	CONSTRAINT FK_ZZT508_CHAM_ZZT000_LANG FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	)

GO


/****** Object:  Table dbo.ZZT513_FUNCTION   ******/
ALTER TABLE  dbo.ZZT513_FUNCTION 
	ADD
	CONSTRAINT FK_ZZT513_FUNC_ZZT000_LANG FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES  dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZZT513_FUNC_ZZT013_FUNC FOREIGN KEY 
	(
		IDFUNCTION
	) REFERENCES  dbo.ZZT013_FUNCTION (
		IDFUNCTION
	)

GO

/****** Object:  Table dbo.ZZT014_POSITION   ******/
ALTER TABLE  dbo.ZZT014_POSITION 
	ADD
	CONSTRAINT FK_ZZT014_POSI_ZZT013_FUNCTION FOREIGN KEY 
	(
		IDFUNCTION
	) REFERENCES  dbo.ZZT013_FUNCTION (
		IDFUNCTION
	)

GO

/****** Object:  Table dbo.ZZT514_POSITION   ******/
ALTER TABLE  dbo.ZZT514_POSITION 
	ADD
	CONSTRAINT FK_ZZT514_POSI_ZZT000_LANG FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES  dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZZT514_POSI_ZZT014_POSI FOREIGN KEY 
	(
		IDPOSITION
	) REFERENCES  dbo.ZZT014_POSITION (
		IDPOSITION
	)

GO

/****** Object:  Table dbo.ZZT515_STATUS  ******/
ALTER TABLE  dbo.ZZT515_STATUS 
	ADD
	CONSTRAINT FK_ZZT515_STAT_ZZT000_LANG FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES  dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZZT515_STATUS_ZZT015_STATUS FOREIGN KEY 
	(
		STATUS
	) REFERENCES  dbo.ZZT015_STATUS (
		STATUS
	)

GO

/****** Object:  Table dbo.ZZT517_MEDAL   ******/
ALTER TABLE  dbo.ZZT517_MEDAL 
	ADD
	CONSTRAINT FK_ZZT517_MEDA_ZZT000_LANG FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES  dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZZT517_MEDAL_ZZT017_MEDAL FOREIGN KEY 
	(
		MEDAL
	) REFERENCES  dbo.ZZT017_MEDAL (
		MEDAL
	)

GO


/****** Object:  Table dbo.ZZT519_REGTYPE   ******/
ALTER TABLE dbo.ZZT519_REGTYPE 
	ADD
	CONSTRAINT FK_ZZT519_REGT_ZZT000_LANG FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZZT519_REGT_ZZT019_REGT FOREIGN KEY 
	(
		TYPE
	) REFERENCES dbo.ZZT019_REGTYPE (
		TYPE
	)

GO

/****** Object:  Table dbo.ZZT526_WEATHER   ******/
ALTER TABLE dbo.ZZT526_WEATHER 
	ADD
	CONSTRAINT FK_ZZT526_WEAT_ZZT000_LANG FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZZT526_WEAT_ZZT026_WEAT FOREIGN KEY 
	(
		IDWEATHER
	) REFERENCES dbo.ZZT026_WEATHER (
		IDWEATHER
	)

GO

/****** Object:  Table dbo.ZZT027_MEDICAL_CLASS   ******/
ALTER TABLE dbo.ZZT027_MEDICAL_CLASS 
	ADD
	CONSTRAINT FK_ZZT027_MEDICAL_CLASS_ZZT005_FEDERATION FOREIGN KEY 
	(
		FEDERATION
	) REFERENCES dbo.ZZT005_FEDERATION (
		FEDERATION
	)

GO









