

/****** Object:  Table dbo.ZZT516_AREA    ******/
ALTER TABLE  dbo.ZZT516_AREA 
	ADD
	CONSTRAINT FK_ZZT516_AREA_ZZT000_LANG FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES  dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZZT516_AREA_ZZT016_AREA FOREIGN KEY 
	(
		AREA
	) REFERENCES  dbo.ZZT016_AREA (
		AREA
	)

GO


/****** Object:  Table dbo.ZZT520_TYPE_TOP   ******/
ALTER TABLE  dbo.ZZT520_TYPE_TOP 
	ADD
	CONSTRAINT FK_ZZT520_TYPE_ZZT000_LANGUAGE FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES  dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZZT520_TYPE_ZZT020_TYPE FOREIGN KEY 
	(
		TYPE
	) REFERENCES dbo.ZZT020_TYPE_TOP (
		TYPE
	)

GO
