ALTER TABLE  dbo.ZZT521_COLOR 
	ADD
	CONSTRAINT FK_ZZT521_COLOR_ZZT000_LANGUAGE FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES  dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZZT521_COLOR_ZZT021_COLOR FOREIGN KEY 
	(
		COLOR
	) REFERENCES  dbo.ZZT021_COLOR 	(	
		COLOR
	)

GO


/****** Object:  Table dbo.ZZT524_ROUND   ******/
ALTER TABLE  dbo.ZZT524_ROUND 
	ADD
	CONSTRAINT FK_ZZT524_ROUND_ZZT000_LANGUAGE FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES  dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZZT524_ROUND_ZZT024_ROUND FOREIGN KEY 
	(
		ROUND
	) REFERENCES dbo.ZZT024_ROUND (
		ROUND
	)

GO


/****** Object:  Table dbo.ZZT522_MODALITY    ******/
ALTER  TABLE  dbo.ZZT522_MODALITY 
	ADD
	CONSTRAINT FK_ZZT522_MODA_ZZT000_LANG FOREIGN KEY 
	(
		IDLANGUAGE
	) REFERENCES  dbo.ZZT000_LANGUAGE (
		IDLANGUAGE
	),
	CONSTRAINT FK_ZZT522_MODA_ZZT022_MODA FOREIGN KEY 
	(
		MODALITY
	) REFERENCES  dbo.ZZT022_MODALITY (
		MODALITY
	)

GO

